version: '3'
services:
  jenkins-slave:
    build: .
    hostname: jenkins-slave-in-docker
    ports:
      - "9022:22"
    volumes:
      - ./ssh:/etc/ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_GID: $DOCKER_GID
