version: '3'
services:
  jenkins-slave:
    build: .
    hostname: jenkins-slave-in-docker
    ports:
      - "9022:22"
    volumes:
      - /srv/docker-jenkins:/srv/jenkins
      - /srv/jenkins/workspace:/srv/jenkins/workspace
      - /srv/jenkins/.ssh/:/host-ssh/:ro
      - ./ssh:/etc/ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_GID: $DOCKER_GID
    restart: always
